# To use the default pimple 'DiC', use Controller::Action. To use Auryn recursive autowiring DiC, use Controller:Action
routes:
  home:
    pattern:  /
    defaults: { _controller: 'HomeController:indexAction', _template: 'home/index.html.twig' }
  login:
    pattern:  /login
    defaults: { _controller: 'HomeController:loginAction', _template: 'home/login.html.twig' }
  dashboard:
    pattern:  /dashboard
    defaults: { _controller: 'DashboardController:indexAction', _template: 'dashboard/index.html.twig' }
  downloads:
    pattern:  /downloads
    defaults: { _controller: 'DownloadsController:indexAction', _template: 'downloads/index.html.twig' }
  admin:
    pattern:  /admin
    defaults: { _controller: 'AdminController:indexAction', _template: 'admin/index.html.twig' }
  admin_servers:
    pattern:  /admin/servers
    defaults: { _controller: 'AdminController:serversAction', _template: 'admin/servers.html.twig' }
  admin_servers_remove_client:
    pattern:  /admin/servers/remove-client
    defaults: { _controller: 'AdminController:removeClientAction' }
    method:   'POST'
  admin_servers_add_client:
    pattern:  /admin/servers/add-client
    defaults: { _controller: 'AdminnController:addClientAction' }
    method:   'POST'